### ISSUE TITLE
[BUG] - Enter op input veld in form met dressed select heeft geen submit als gevolg

### ISSUE THREAD

**Issue by SBylemans** [milieuinfo/webcomponent-vl-ui-select#120]
**Omschrijf het probleem**
Wanneer we op enter duwen op een inputveld in een form met een gedressede select, dan opent de select.

**Hoe te reproduceren**

```
        <form id="inspraak-search-publiek" novalidate
            @reset="${(e) => setTimeout(this._searchAfterReset.bind(this), 50, e)}">
          <section>
            <div>
              <label is="form-label" for="trefwoord">Trefwoord</label>
              <input is="vl-input-field" id="trefwoord" type="text" name="trefwoord" value="" block placeholder="Zoek op trefwoord" />
            </div>
            <div>
              <label is="form-label" for="betrokken-gemeentes">Betrokken gemeente</label>
              <select is="vl-select" id="betrokken-gemeentes" name="betrokken-gemeentes" block data-vl-select-deletable>
               <option placeholder selected value="">Alle gemeentes</option>
              </select>
            </div>
          </section>
          <div>
            <button is="vl-button" id="search-button" @click="${this._searchWithNewValues}">
              <span is="vl-icon" icon="search" before></span>
              Zoeken
            </button>
          </div>
        </form>


    this._betrokkenGemeentes = queryById(this._search)('betrokken-gemeentes');

      this._betrokkenGemeentes.dress({
        callbackFn: (select) => this.gemeentes.map(
          g => {
            return {label: g, value: g}
          })
      });
```

**Gewenst gedrag**
Wanneer op enter geduwd wordt op eender welk veld in een form, moet de submit uitgevoerd worden. 

Echter de gedressede select zal ook nog een mogelijkheid moeten voorzien om via toetsenbord een waarde te selecteren.

**Omgeving (gelieve aan te vullen):**
 - Browser [vb. chrome, safari]
 - Versie [vb. 22]
 - Versie component 4.1.0

**Comment by coemans** [comment]
Gedrag is reproduceerbaar bij Webuniversum en zal met hen besproken worden.

**Comment by coemans** [comment]
De toegankelijkheidsexpert geeft alvast aan dat zolang er een submit button is, het formulier toegankelijk is en dit gedrag geen probleem hoeft te zijn. Het klopt wel dat een enter op een native input (ook op een select) normaal gezien het formulier moet versturen. Dat is niet het geval bij de dressed variant van vl-select. Aangezien een deel van het gedrag browser afhankelijk is en er achterliggend een dependency gebruikt wordt, is het blijkbaar moeilijk om dit centraal op te lossen. Na een kosten-batenanalyse werd besloten om hier centraal voorlopig geen gevolg aan te geven.

Indien dit alsnog een probleem blijkt, kan er natuurlijk altijd gewerkt worden met de native select die ook conform de huisstijl is.
