### ISSUE TITLE
[BUG] - dressed select verliest placeholder te laat indien choices vervangen wordt

### ISSUE THREAD

**Issue by FreekRombauts** [milieuinfo/webcomponent-vl-ui-select#135]
**Omschrijf het probleem**
Een dressed select verliest zijn placeholder nadat de eerste keer een optie gekozen is. Dit heeft 2 gevolgen:
* Het is dan niet meer mogelijk om het geselecteerde item te verwijderen door de placeholder te kiezen.
* Als het geselecteerde item verwijderd wordt, dan wordt de select leeg, ipv de placeholder tekst te bevatten

**Hoe te reproduceren**

Maak een dressed select, met alleen een placeholder option:

```
          <select is="vl-select" id="betrokken-gemeentes" name="betrokken-gemeentes" 
            data-vl-select
            data-vl-block
            data-vl-select-deletable>
            <option placeholder selected value="">Alle gemeentes</option>
          </select>
```

Vervang de options als de select klaar is:

```
    let dropdown = ...
    dropdown.ready().then(() => {
      dropdown.choices = [{label: 'A', value:'A'}, {label: 'B', value: 'B'}];
    });
```

Dit vervangt alle options, inclusief de placeholder option. Er is geen placeholder in de nieuwe lijst, dus die hoort weg te zijn. Visueel staat de placeholder er echter nog:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/58428396/93457263-0c8a3100-f8df-11ea-9d9f-f22f3087255f.png">

Zodra je de dropdown opent en een item selecteert, verdwijnt de placeholder wel:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/58428396/93457353-2461b500-f8df-11ea-98c4-a475911f3ccc.png">
<img width="364" alt="image" src="https://user-images.githubusercontent.com/58428396/93457529-668af680-f8df-11ea-8b2c-e17dd9d90496.png">

**Gewenst gedrag**
Placeholder is direct weg.

**Omgeving (gelieve aan te vullen):**
 - Browser: safari
 - Versie component: 3.2.1

**Comment by kevcraey** [comment]
https://www.milieuinfo.be/jira/browse/UIG-2210
