### ISSUE TITLE
[BUG] - Focus call heeft geen effect bij dressed variant

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-select#137]
**Omschrijf het probleem**
focus zorgt wel dat de browser naar de component gaat, maar visueel verandert de component niet.

**Hoe te reproduceren**
na de focus call moet de component visueel aangeven dat deze gefocussed is.

**Comment by coemans** [comment]
Bij een gewone variant lijkt alles correct te werken incl. stijl. Bij een dressed variant lijkt de focus niet te werken. Ik zal dat issue oplossen in kader van dit ticket.

![focus](https://user-images.githubusercontent.com/11139249/96227892-13b36600-0f95-11eb-872b-3219b37b89ce.gif)

**Comment by FreekRombauts** [comment]
@coemans , getest in alle browsers, focus werkt nu.
