### ISSUE TITLE
[BUG] - error attribuut op surrounding div verdwijnt niet 

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-select#141]
**Omschrijf het probleem**
In IBO, bij het gebruik van de mul

**Hoe te reproduceren**

- Multiselect + nog andere required velden in form zetten
- multiselect invullen met 1 of meer opties (alle andere velden leeg laten) en terug leeg maken
- form valideren door de submit 
- alle velden zouden rood moeten zijn
- opnieuw de multiselect opvullen => geeft errorAttribute op component (errormessage verdwijnt wel)
- Optioneel: de form opnieuw blijven submitten geeft geen verandering voor de error op deze component

vl-select--error wordt niet van de surrounding div gehaald

**Gewenst gedrag**
Error attribute van component halen wanneer deze wel degelijk valid is

**Screenshots**
<img width="918" alt="Screenshot 2020-11-19 at 17 25 57" src="https://user-images.githubusercontent.com/8820456/99694178-6b5d5980-2a8c-11eb-8583-b3fdd553f421.png">
<img width="915" alt="Screenshot 2020-11-19 at 17 25 36" src="https://user-images.githubusercontent.com/8820456/99694186-6d271d00-2a8c-11eb-8b7b-86370cbc5c6e.png">

**Omgeving (gelieve aan te vullen):**
 - Browser chrome
 - Versie component 4.0.8

**Extra info**
Blijkbaar was deze issue al gekend, maar we vinden geen gelijkaardige bug terug. Mogelijks is dit een terugkerend probleem.

**Comment by coemans** [comment]
Het probleem is niet meer reproduceerbaar met de meest recente versie van vl-ui-multiselect in combinatie met vl-ui-form-validation. Indien er alsnog applicatief problemen zouden zijn, kan het issue opnieuw geopend worden.
