### ISSUE TITLE
[BUG] - Programmatisch selectie verwijderen opent de keuzelijst

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-select#25]
**Omschrijf het probleem**
removeActive() opent de keuzelijst na het verwijderen van active item

**Comment by coemans** [comment]
Probleem ondertussen niet meer reproduceerbaar, vermoedelijk door upgrades. Ik heb voor de zekerheid wel een e2e test toegevoegd.

**Comment by coemans** [comment]
Probleem stelt zich wel nog bij variant met `data-vl-select-deletable` attribuut.

**Comment by FreekRombauts** [comment]
@coemans , getest en gereviewed, ziet er ok uit.
