### ISSUE TITLE
[BUG] - Select/multiselect disabled

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-select#26]
**Omschrijf het probleem**
Webcomponents Chrome Issue:

In disabled mode kan ik op chrome de keuzelijst openen maar niet meer sluiten.
In safari gaat de keuzelijst niet open.

Op de webuniversum site lijkt het wel te werken op chrome (geen keuzelijst dropdown in disabled mode)

**Comment by driesva** [comment]
In Firefox hetzelfde issue.  Als je `disable()` aanroept zie je toch nog de lijst en kan je nog zaken selecteren. Zie:
<img width="1143" alt="select disabled" src="https://user-images.githubusercontent.com/29454303/66210333-d9449700-e6b9-11e9-935f-45e631dd9e56.png">

Keuzelijst zou volledig gedisabled moeten zijn.

**Comment by coemans** [comment]
E2E test om het probleem boven te halen:

```JavaScript
it('als gebruiker zie ik wanneer een select disabled is en kan ik niets selecteren', async () => {
    const select = await vlSelectPage.getDefaultSelect();
    const disabledSelect = await vlSelectPage.getDisabledSelect();
    await assert.eventually.isFalse(select.isDisabled());
    await assert.eventually.isTrue(disabledSelect.isDisabled());
    await assert.eventually.equal(disabledSelect.getSelectedValue(), 'België');
    await disabledSelect.selectByValue('Duitsland');
    await assert.eventually.notEqual(disabledSelect.getSelectedValue(), 'Duitsland');
});
```

**Comment by kevcraey** [comment]
https://www.milieuinfo.be/jira/browse/UIG-2212
