### ISSUE TITLE
[BUG] - de combobox verschijnt niet boven de dropzone

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-select#55]
**Omschrijf het probleem**
De lijst verschijnt niet boven de dropzone

**Hoe te reproduceren**
Dropzone in combinatie met select

**Gewenst gedrag**
Lijst volledig zichtbaar zonder dropzone op achtergrond

**Screenshots**
![image](https://user-images.githubusercontent.com/29454303/67092060-98b34600-f1ae-11e9-98ff-d5ef6fe2585c.png)

**Omgeving (gelieve aan te vullen):**
 - Fx 71.0b1 (64-bit)

**Extra info**
Pull request https://github.com/milieuinfo/webcomponent-vl-ui-select/pull/54#issue-329699177

**Comment by coemans** [comment]
Probleem opgelost in PR #56.
