### ISSUE TITLE
[BUG] - Resultatenlijst onvoldoende bij zoeken

### ISSUE THREAD

**Issue by blens-test** [milieuinfo/webcomponent-vl-ui-select#70]
**Omschrijf het probleem**
Select met search, zoeken op item, maximum worden er 4 resultaten weergegeven

**Gewenst gedrag**
Indien je een select hebt van 100 items wordt deze getooond met een scrollbar. Het zoekresultaat zou ook zo moeten reageren. --> lijst met zoekresultaten die voldoen aan de search, indien te groot, tonen met scrollbar

**Comment by coemans** [comment]
Aangezien dit gedrag zo voorzien werd door Webuniversum, heb ik voor de zekerheid navraag gedaan om te informeren of dit geen onderdeel van de UI/UX is. Bijkomend heb ik geïnformeerd of het niet verwarrend is dat op elke website van de overheid er 4 resultaten getoond worden en bij ons meer. Door afwijkend functioneel gedrag zouden we namelijk net verwarring kunnen introduceren.

Conclusie was dat het aantal zoekresultaten gerust en zonder problemen mag verhoogd worden.

Technisch houdt dit in dat we de _searchResultLimit_ variable configureerbaar maken via de API.

**Comment by coemans** [comment]
Uitbreiding voorzien zodat de aantal resultaten limiet geconfigureerd kan worden. Geen unit testen voorzien omdat de wijziging volledig in de code van Webuniversum zit. Er wordt later wel een end2end test toegevoegd.

In #28 zal ook deze wijziging gecommuniceerd of gepushed worden naar Webuniversum.
