### ISSUE TITLE
[BUG] - Icoon om optie te verwijderen is verkeerd uitgelijnd

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-select#92]
**Omschrijf het probleem**
Icoon om optie te verwijderen is verkeerd uitgelijnd

**Screenshots**
![image-2020-02-17-10-57-17-877](https://user-images.githubusercontent.com/1628243/75774684-c01b4180-5d50-11ea-828f-9dcc477d9bb3.png)

**Comment by coemans** [comment]
Probleem is niet meer reproduceerbaar in de meest recente versie.
